In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
type(L)

list

In [5]:
type(A)

numpy.ndarray

In [6]:
for e in L:
    print(e)

1
2
3


In [8]:
for e in A:
    print(e)

1
2
3


In [9]:
L.append(4)

In [10]:
print(L)

[1, 2, 3, 4]


In [11]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

## Size of Array is fixed

In [12]:
L + [5]

[1, 2, 3, 4, 5]

In [13]:
L

[1, 2, 3, 4]

In [14]:
A + np.array([4])

array([5, 6, 7])

In [15]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [16]:
2 * A

array([2, 4, 6])

In [17]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
L2 = []
for e in L:
    L2.append(e + 3)

In [19]:
L2

[4, 5, 6, 7]

In [20]:
L2 = [e + 3 for e in L]

In [21]:
L2

[4, 5, 6, 7]

In [22]:
L2 = []
for e in L:
    L2.append(e**2)

L2

[1, 4, 9, 16]

In [23]:
A + 3

array([4, 5, 6])

In [24]:
A ** 2

array([1, 4, 9], dtype=int32)

In [26]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [27]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])