In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
10 * np.ones((3,4))

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [6]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [8]:
np.eye((10000))

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [9]:
np.random.random()

0.8855115370457997

In [11]:
np.random.random((2,3))

array([[0.84869834, 0.20051878, 0.79162072],
       [0.64000598, 0.10066468, 0.87050017]])

In [13]:
np.random.randn(2,3)

array([[ 0.29965237, -1.38477449, -0.53621242],
       [-0.77152666,  1.03677637,  0.00388885]])

In [21]:
R = np.random.randn(10000000)

In [22]:
R.mean()

6.822163995286994e-05

In [23]:
np.mean(R)

6.822163995286994e-05

In [24]:
R.var()

1.0008208774424843

In [25]:
R.std()

1.0004103545258236

In [26]:
R = np.random.randn(10000,3)

In [27]:
R

array([[ 0.20282476, -1.16589177, -2.73108113],
       [-0.68368757,  0.39982211,  0.53567892],
       [ 0.35315997,  0.37537166, -0.05104125],
       ...,
       [-0.05462478,  2.81509207, -0.50569184],
       [ 0.81733147, -1.37106364,  0.21745253],
       [ 0.15529052, -0.77693179, -2.02274903]])

In [29]:
np.cov(R).shape

(10000, 10000)

In [30]:
np.cov(R, rowvar = False)

array([[ 1.00977473e+00,  9.85863968e-03, -9.06053551e-04],
       [ 9.85863968e-03,  1.00488071e+00,  7.76144685e-03],
       [-9.06053551e-04,  7.76144685e-03,  1.00637139e+00]])

In [59]:
np.random.randint(0,10,size = (3,3))

array([[7, 8, 8],
       [9, 8, 8],
       [6, 8, 7]])

In [60]:
np.random.choice(10, size = (3,3))

array([[5, 8, 2],
       [1, 0, 5],
       [6, 0, 4]])